#ATTX ETL API specification
swagger: '2.0'

info:
  version: "0.0.1"
  title: ATTX ETL API
  description: ATTX ETL internal API for communication between ETL tool and Graph Manager component.
  contact:
    name: "ATTX project"
    url: http://helsinki.fi/library
  license:
    name: "MIT"
paths:
  /workflow:
    get:
      description: |
        This operation gathers all the information necessary to describe the workflows, steps and relationships between them
      summary: |
        List the latest workflow and associated steps.
      parameters:
       -
        name: modifiedSince
        in: query
        description: Size of array
        required: false
        type: string
        format: date-time
      produces:
        - text/turtle
        - application/ld+json
      responses:
        200:
          description: Successful response.
    post:
      responses:
        500:
          description: This operation cannot be Perfomed.

  /activity:
    get:
      description: |
        This operation gathers all the information necessary to describe the activities, datasets and how the datasets are acquired (input dataset) or produced (output dataset).
      summary: |
        Retrieve the latest activity and associated datasets.
      produces:
        - text/turtle
        - application/ld+json
      parameters:
       -
        name: modifiedSince
        in: query
        description: Size of array
        required: false
        type: string
        format: date-time
      responses:
        200:
          description: Successful response.
    post:
      responses:
        500:
          description: This operation cannot be Perfomed.
