---
swagger: "2.0"
info:
  description: "ATTX WF internal API for communication between wf tool and Graph\
    \ Manager component."
  version: "0.1"
  title: "ATTX wf API"
  contact:
    name: "ATTX project"
    url: "http://helsinki.fi/library"
  license:
    name: "MIT"
tags:
- name: "wfAPI"
  description: "Internal wfAPI for workflow metadata"
  externalDocs:
    description: "just use it"
    url: "http://helsinki.fi/library"
schemes:
- "http"

paths:
  /activity:
    get:
      tags:
      - "wfAPI"
      summary: "Retrieve the latest activity and associated datasets.\n"
      description: "This operation gathers all the information necessary to describe\
        \ the activities, datasets and how the datasets are acquired (input dataset)\
        \ or produced (output dataset).\n"
      operationId: "api.activity.activity_get"
      produces:
      - "text/turtle"
      - "application/ld+json"
      parameters:
      - name: "modifiedSince"
        in: "query"
        description: "Date since last check."
        required: false
        type: "string"
        format: "date-time"
      responses:
        200:
          description: "Successful response."
      x-tags:
      - tag: "wfAPI"
    post:
      tags:
      - "wfAPI"
      summary: "Creating a new activity is not permitted.\n"
      operationId: "api.activity.activity_post"
      parameters: []
      responses:
        405:
          description: "This operation cannot be perfomed."
      x-tags:
      - tag: "wfAPI"
  /workflow:
    get:
      tags:
      - "wfAPI"
      summary: "List the latest workflow and associated steps.\n"
      description: "This operation gathers all the information necessary to describe\
        \ the workflows, steps and relationships between them\n"
      operationId: "api.workflow.workflow_get"
      produces:
      - "text/turtle"
      - "application/ld+json"
      parameters:
      - name: "modifiedSince"
        in: "query"
        description: "Date since last check."
        required: false
        type: "string"
        format: "date-time"
      responses:
        200:
          description: "Successful response."
      x-tags:
      - tag: "wfAPI"
    post:
      tags:
      - "wfAPI"
      summary: "Creating a new workflow is not permitted.\n"
      operationId: "api.workflow.workflow_post"
      parameters: []
      responses:
        405:
          description: "This operation cannot be Perfomed."
      x-tags:
      - tag: "wfAPI"
definitions: {}
